### PR TITLE
Added NUnitMultitest task

### PR DESCRIPTION
**Pull request by sorin-bolos**
-this task allows multiple tests sets to be run in parallel
by starting multiple NUnit processes

### CODE REVIEW

**Comment by gluck** [comment]
Thx !

Sounds a bit troublesome to have an extra task just for the sake of running tests in parallel no ?

**Comment by sorin-bolos** [comment]
So you're saying that this should be done differently or that it shouldn't be done at all?

**Comment by gluck** [comment]
I'm wondering if it could be done differently, as an option to the current nunit task (e.g. `parallel_forks = true`)

**Comment by sorin-bolos** [comment]
Ok, but the existing task takes a single test filter as a parameter and we need a list of filters to get them running in parallel. We'll need either to change the parameter or add a new one. Which do you prefer?

**Pull request closed without merging**
