### PR TITLE
Fix opencover-nunit when nunit not cached

### PR DESCRIPTION
**Pull request by ngyukman**

### CODE REVIEW

**Comment by gluck** [comment]
Does that work with parallel builds ? (seems to be goind a bit backwards from #24 no ?) cc @reeflog

**Comment by florian-gandon** [comment]
Depending of where is called "getNunitFolder()". For instance, if it's used in a closure in the plugin configuration like it was the case before. Looking at the code I don't expect that anymore.
That being said, I'm not feeling confident with having a simple get with such side effect (downloading NUnit). A alternative could be to download explictly NUnit from OpenCover. I'm not sure it's better.
So, it looks good enough for me.

**Comment by gluck** [comment]
maybe renaming `getNunitFolder` to `getCachedOrDownloadNUnit` or something like that would make the trick ? (because changing opencover doesn't seem good either)

**Comment by timotei** [comment]
Well, isn't it easier/better to just have something like `opencover.dependsOn nunit`? (Or `withType(Nunit)...` thingy

**Comment by gluck** [comment]
opencover runs instead-of nunit (no need to run UTs twice), so it can't depend I guess

**Comment by muryoh** [comment]
Maybe we could do something like the jacoco plugin does to the standard
test task. IIRC it customizes it to specify jacoco specific stuff on the
jvm args

**Comment by muryoh** [comment]
Something like that: https://github.com/gradle/gradle/blob/master/subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoPluginExtension.java#L100

**Pull request merged**
