### PR TITLE
Use result culture only for v3 reports

### PR DESCRIPTION
**Pull request by florian-gandon**
Set the merged test report always in "en-US" culture and format
properly times to avoid compatibility issues with other tools. NUnit v2
was always saving double like "1.123" even if the culture was, for
instance, fr-FR.

### CODE REVIEW

**Comment by gluck** [comment]
Is there an issue open on NUnit v3 for this change/regression when outputting V2 reports ?
Maybe they'd like to fix it ?

**Comment by florian-gandon** [comment]
I didn't check but it looks like a bug fix between v2 and v3. Before they were putting the culture but, basically, not using it

**Comment by gluck** [comment]
probably, but maybe they didn't intend to change the V2 format behavior, just the V3 one, having an issue ref would make it clear, i.e. no guessing :)

**Comment by florian-gandon** [comment]
I've opened a issue on nunit project. https://github.com/nunit/nunit/issues/1401

**Comment by florian-gandon** [comment]
It's fixed in NUnit 3..2.
We can close this change but I need to roll back the previous one.
https://github.com/Ullink/gradle-nunit-plugin/pull/24

**Pull request closed without merging**
